### ISSUE TITLE
Empty settings structure when checking camera compatibility

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#242]
```
2017-03-12 19:50:15,617 - octoprint - ERROR - Exception on /api/camera/is-camera-supported [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "platforms/common/AstroBox/src/octoprint/server/util.py", line 85, in decorated_view
  File "platforms/common/AstroBox/src/astroprint/api/camera.py", line 19, in isCameraSupportedByAstrobox
  File "platforms/common/AstroBox/src/astroprint/camera/v4l2/__init__.py", line 356, in settingsStructure
TypeError: 'NoneType' object is not iterable
```

Camera is a Microsoft vx-6000

**Comment by CoDanny** [comment]
The problem was that the driver couldn't read from the camera (likely an unsupported camera) but the handling of the error was wrong. Now fixed.
