### ISSUE TITLE
Error uploading file to astrobox

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#246]
```
2017-03-21 00:30:20,293 - octoprint - ERROR - Exception on /api/files/local [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "platforms/common/AstroBox/src/octoprint/server/util.py", line 85, in decorated_view
  File "platforms/common/AstroBox/src/astroprint/api/files.py", line 158, in uploadPrintFile
  File "platforms/common/AstroBox/src/astroprint/printfiles/__init__.py", line 272, in addFile
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 2585, in save
    dst = open(dst, 'wb')
IOError: [Errno 117] Structure needs cleaning: '/AstroBoxFiles/uploads/04mm_Thin__Wall_cali-Folgertech--PETG-custom.gcode'
```

**Comment by CoDanny** [comment]
The problem is that the filesystem was corrupt. Adding a better way to report this.
