### ISSUE TITLE
Error connecting to WiFi network

### ISSUE THREAD

**Issue by CoDanny** [AstroPrint/AstroBox#258]
```
2017-04-20 04:05:39,755 - octoprint - ERROR - Exception on /api/settings/network/active [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "platforms/common/AstroBox/src/octoprint/server/util.py", line 85, in decorated_view
  File "platforms/common/AstroBox/src/astroprint/api/settings.py", line 87, in setWifiNetwork
  File "platforms/common/AstroBox/src/astroprint/network/debian.py", line 408, in setWifiNetwork
  File "/usr/local/lib/python2.7/dist-packages/NetworkManager.py", line 117, in proxy_call
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.NetworkManager.InvalidProperty: Failed to determine AP security information
```

**Comment by CoDanny** [comment]
The raise of the exception is expected. The user used an access point that's not publishing compatible security information. We could cleanup the message if we would know the actual settings of the WiFi router. In the meantime, we close this issue.
