### ISSUE TITLE
Error trying to run from source (OrangePi-Raspbian)

### ISSUE THREAD

**Issue by moracabanas** [AstroPrint/AstroBox#298]
Im running Raspbian on Orange Pi Zero. I have installed all of the Github list to properly run Astroprint. Here is the process I needed to get no errors on installation:

```
sudo apt-get update
sudo apt-get install software-properties-common
sudo apt-get install git
(---downloaded and installed arm Java8 JRE---)
git clone https://github.com/AstroPrint/AstroBox.git
sudo apt-get install rubygems
sudo apt-get install ruby-dev 
sudo gem install sass
sudo apt-get install python-dev
sudo apt-get install python-pip
cd Astroprint/
sudo pip install -r requirements.txt
```

So downloaded Astroprint to /root and manage to install all the dependencies listed on github, but when I run `sudo python ./run --config /etc/astrobox/config.yaml --host 127.0.0.1` I get this:

```
Traceback (most recent call last):
  File "./run", line 22, in <module>
    import octoprint
  File "/root/AstroBox/src/octoprint/__init__.py", line 5, in <module>
    from octoprint.server import Server
  File "/root/AstroBox/src/octoprint/server/__init__.py", line 52, in <module>
    from octoprint.server.util import LargeResponseHandler, ReverseProxied, restricted_access, PrinterStateConnection, admin_validator, UrlForwardHandler, user_validator
  File "/root/AstroBox/src/octoprint/server/util.py", line 33, in <module>
    from astroprint.boxrouter import boxrouterManager
  File "/root/AstroBox/src/astroprint/boxrouter/__init__.py", line 32, in <module>
    from astroprint.software import softwareManager
  File "/root/AstroBox/src/astroprint/software.py", line 37, in <module>
    import apt.debfile
ImportError: No module named apt.debfile
```
Not to mention If you first do:
 `sudo service astrobox stop` you get:
`Failed to stop astrobox.service: Unit astrobox.service not loaded.`

Is there something i missed on installation?

**Comment by CoDanny** [comment]
We don't support any other platform than the Raspberry PI.
