### ISSUE TITLE
Astrobox loses connection when turning on

### ISSUE THREAD

**Issue by Alfonsopl** [AstroPrint/AstroBox#339]
This always happens when astrobox is  turning on and his saved wifi connection is turning on too (not tested on lost connection and reconnect when is on)

Astrobox actually connect to internet, but you can´t  see the box on cloud.
You can access by browser (connected at the same wifi network, not hot spot) an see it without connection:

<img width="467" alt="captura de pantalla 2018-01-18 a las 8 51 30" src="https://user-images.githubusercontent.com/14834229/35089512-7967e972-fc37-11e7-8a57-65ef1f46e370.png">

But when you go to settings there is an error and network setting tabs is completely empty:
<img width="1127" alt="captura de pantalla 2018-01-18 a las 9 13 24" src="https://user-images.githubusercontent.com/14834229/35089570-a122fd4e-fc37-11e7-964e-98a7e5a377d5.png">

the logs only recorded this error a day ago, when it worked perfectly:

```
2018-01-17 12:56:07,506 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "git-repos/AstroBox/src/ext/pynetworkmanager/NetworkManager.py", line 100, in handle_signal
  File "git-repos/AstroBox/src/astroprint/network/debian.py", line 155, in propertiesChanged
AttributeError: 'ActiveConnection' object has no attribute 'State'
2018-01-17 12:57:02,950 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "git-repos/AstroBox/src/ext/pynetworkmanager/NetworkManager.py", line 100, in handle_signal
  File "git-repos/AstroBox/src/astroprint/network/debian.py", line 155, in propertiesChanged
AttributeError: 'ActiveConnection' object has no attribute 'State'
2018-01-17 12:57:02,956 - astroprint.network.debian - INFO - Network Global State Changed, new(connecting)
2018-01-17 12:57:02,974 - dbus.connection - ERROR - Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "git-repos/AstroBox/src/ext/pynetworkmanager/NetworkManager.py", line 100, in handle_signal
  File "git-repos/AstroBox/src/astroprint/network/debian.py", line 155, in propertiesChanged
AttributeError: 'ActiveConnection' object has no attribute 'State'
```

**Comment by julianCast** [comment]
Same problem using 0.11.0
```
2018-02-14 09:40:08,568 - com_astroprint_astrobox_plugins_externalcomms.requests_processor - ERROR - Error processing request [system.networkSettings]

Traceback (most recent call last):

  File "/home/pi/AstroBox-Plugins/com_astroprint_astrobox_plugins_externalcomms/requests_processor.py", line 70, in processRequest

    method(payload.get('data'), sendResponse)

  File "/home/pi/AstroBox-Plugins/com_astroprint_astrobox_plugins_externalcomms/requests_handler/system.py", line 45, in networkSettings

    self._services['system'].networkSettings(data,sendResponse)

  File "/home/pi/AstroBox/src/astroprint/plugin/services/system.py", line 262, in networkSettings

    'networks': nm.getActiveConnections(),

  File "/home/pi/AstroBox/src/astroprint/network/debian.py", line 346, in getActiveConnections

    if c.State == self._nm.NM_ACTIVE_CONNECTION_STATE_ACTIVATED:

AttributeError: 'ActiveConnection' object has no attribute 'State'
```
