### ISSUE TITLE
C920 Camera (Still picture) doesn't work when set to rotate image

### ISSUE THREAD

**Issue by daphishbowl** [AstroPrint/AstroBox#560]
Not sure what happened but I have been using the C920 forever and I noticed lately it wasn't working after download one of the updates.   Got time to dig in a little and it looks like if I set the camera to have "no rotation" in the settings it works.  Once I choose any rotation I just get an error.  Tested using the App, locally using Chrome Version 79.0.3945.130 which all generate the same issue.

Is there a missing package that handles the rotation that needs to be installed?
I looked at the logs and /var/log/messages and nothing really there about camera issues.

Astrobox.log just shows
--------------
2020-03-19 22:44:46,738 - astroprint.webrtc - INFO - Closing all streaming sessions
2020-03-19 22:44:46,740 - astroprint.camera.v4l2.gstreamer - INFO - There are 0 local peers left
2020-03-19 22:44:46,823 - astroprint.camera.v4l2.gstreamer - INFO - Camera detected on /dev/video0
2020-03-19 22:44:46,834 - astroprint.camera.v4l2.gstreamer - INFO - Found camera HD Pro Webcam C920, encoding: h264 and size: 640x480. Source used: USB

2020-03-19 22:45:03,511 - octoprint.server.util - INFO - New connection from client [IP address: 192.168.xx.xx, Session id: dkvzyoqi]
2020-03-19 22:45:10,813 - astroprint.camera.v4l2.gstreamer.process.pipelines.h264 - INFO - Pipeline destroyed
2020-03-19 22:45:30,879 - astroprint.camera.v4l2.gstreamer.process.pipelines.h264 - INFO - Pipeline destroyed

Good log without rotation looks like it dumps an error but seems to work
-----------------------
2020-03-19 22:45:50,592 - astroprint.camera.v4l2.gstreamer.pipeline - ERROR - Unable to re-start pipeline process.
2020-03-19 22:45:50,593 - astroprint.camera.v4l2.gstreamer.pipeline - ERROR - Error during photo capture: no_process
2020-03-19 22:45:50,595 - astroprint.boxrouter - ERROR - Error raised during send: [Errno 32] Broken pipe
2020-03-19 22:45:50,597 - astroprint.boxrouter.handlers - ERROR - Error sending [printerCommand] response: [SSL: BAD_LENGTH] bad length (_ssl.c:1747)
Traceback (most recent call last):
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/__init__.py", line 83, in request
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/requesthandler.py", line 60, in printerCommand
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/requesthandler.py", line 231, in _handleCommandGroup
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/requesthandler.py", line 270, in photo
  File "git-repos/AstroBox/src/astroprint/camera/__init__.py", line 474, in get_pic_async
  File "git-repos/AstroBox/src/astroprint/camera/v4l2/gstreamer/__init__.py", line 221, in _doGetPic
  File "git-repos/AstroBox/src/astroprint/camera/v4l2/gstreamer/pipeline.py", line 187, in takePhoto
  File "git-repos/AstroBox/src/astroprint/camera/v4l2/gstreamer/pipeline.py", line 273, in _sendReqToProcess
  File "git-repos/AstroBox/src/astroprint/camera/v4l2/gstreamer/pipeline.py", line 304, in __addReq
  File "git-repos/AstroBox/src/astroprint/camera/v4l2/gstreamer/pipeline.py", line 172, in postprocesing
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/requesthandler.py", line 267, in doneWithPhoto
  File "git-repos/AstroBox/src/astroprint/boxrouter/handlers/__init__.py", line 80, in sendResponse
  File "git-repos/AstroBox/src/astroprint/boxrouter/__init__.py", line 79, in send
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 198, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=True))
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 243, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/ssl.py", line 753, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 719, in send
    v = self._sslobj.write(data)
SSLError: [SSL: BAD_LENGTH] bad length (_ssl.c:1747)
2020-03-19 22:45:50,625 - astroprint.boxrouter - ERROR - Error raised during send: [Errno 32] Broken pipe
2020-03-19 22:45:50,628 - astroprint.boxrouter - INFO - BoxRouter socket closed event with [1006]: Going away - server(1) / client(1)
2020-03-19 22:45:50,631 - astroprint.boxrouter - INFO - Waiting 2 secs before retrying...
2020-03-19 22:45:51,794 - astroprint.camera:CameraInactivity - WARNING - Already running
2020-03-19 22:45:52,641 - astroprint.boxrouter - INFO - Retrying boxrouter connection. Retry #1
2020-03-19 22:45:53,146 - astroprint.boxrouter - INFO - Connected to astroprint service

Version I am using are :
   Astrobox Touch v0.17(4)
   Astrobox Touch UI v0.9.2

**Comment by CoDanny** [comment]
This has been fixed in release 0.18(0) which is available in the Beta Channel
